### ISSUE TITLE
License for the homepage repository

### ISSUE THREAD

**Issue by xzyaoi** [Requarks/wiki-site#20]
Hi, thanks for the awesome work :). I really like the style of the homepage, i.e. the https://wiki.js.org/. I am wondering what is the license for this repository and if it is allowed for me to use the same style, but change the contents for my projects?

Best,
Xiaozhe

**Comment by NGPixel** [comment]
The layout design is based off https://themeforest.net/item/saasland-creative-html5-template-for-saas-startup-agency/22712080

You would need to purchase a license from them.
