### ISSUE TITLE
View on GitHub button links to newsletter page

### ISSUE THREAD

**Issue by thedavidgay** [Requarks/wiki-site#6]
On the home page, the "View on GitHub" button links to `/newsletter` rather than GitHub:

![Wiki_js](https://user-images.githubusercontent.com/1376599/59123898-56d6e100-892c-11e9-9c3d-23d486edbdc2.png)

From the page source:
```html
<a href="/newsletter" class="mt-5 mx-0 v-btn v-btn--large v-btn--router theme--dark primary">
  <div class="v-btn__content">View on GitHub</div>
</a>
```

**Comment by NGPixel** [comment]
Fixed, thanks!
